### PR TITLE
validator, close #121

### LINKED ISSUE #121: Validation layer

### PR DESCRIPTION
**Pull request by roman-duck**

### CODE REVIEW

**Comment by ArtemKrayevskiy** [comment]
Validator.validate function has to get any arguments to validate? For example, a book, or a user?

**Comment by roman-duck** [comment]
isbn check still present in the Book constructor

**Comment by roman-duck** [comment]
Should be implemented behavior for empty validator

**Comment by ArtemKrayevskiy** [comment]
What should an empty validator validate?

**Comment by roman-duck** [comment]
In the client code validation rules may be added dynamically. 
It means, in the client code may be a situation when the validator has no rules and method validate() will execute.
So, when the validator has no rules, any structure is valid.

**Review by mvchn — APPROVED** [review]

**Pull request merged**
